export interface RequestJson {
  ID_TIPO_LOGISTICA: number;
  nombre_ciudad: string;
  DETALLE_ENVIO_1: string;
  DETALLE_ENVIO_2: string;
  DETALLE_ENVIO_3: string;
  ID_CIUDAD_ORIGEN: string;
  ID_CIUDAD_DESTINO: string;
  ID_DESTINATARIO_NE_CL: string;
  RAZON_SOCIAL_DESTI_NE: string;
  NOMBRE_DESTINATARIO_NE: string;
  APELLIDO_DESTINATAR_NE: string;
  DIRECCION1_DESTINAT_NE: string;
  SECTOR_DESTINAT_NE: string;
  TELEFONO1_DESTINAT_NE: string;
  TELEFONO2_DESTINAT_NE: string;
  CODIGO_POSTAL_DEST_NE: string;
  ID_REMITENTE_CL: string | undefined;
  RAZON_SOCIAL_REMITE: string | undefined;
  NOMBRE_REMITENTE: string | undefined;
  APELLIDO_REMITE: string | undefined;
  DIRECCION1_REMITE: string | undefined;
  SECTOR_REMITE: string;
  TELEFONO1_REMITE: string | undefined;
  TELEFONO2_REMITE: string;
  CODIGO_POSTAL_REMI: string;
  ID_PRODUCTO: string;
  CONTENIDO: string;
  NUMERO_PIEZAS: number;
  VALOR_MERCANCIA: number;
  VALOR_ASEGURADO: number;
  LARGO: number;
  ANCHO: number;
  ALTO: number;
  PESO_FISICO: number;
  LOGIN_CREACION: string | undefined;
  PASSWORD: string | undefined;
}
